services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/.env:/app/.env
    ports:
      - "3000:3000"
    command: npm run start:dev
    working_dir: /app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./client/.env:/app/.env
    ports:
      - "4200:4200"
    command: npm run start
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
